# Generated by Django 6.0.1 on 2026-01-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name': 'SocialLinks', 'verbose_name_plural': 'Social Links'},
        ),
    ]
